import Foundation

/// A one-time enrollment code generated by the parent.
/// The child device uses this code to link itself to a ChildProfile.
///
/// Codes are 8 uppercase alphanumeric characters (excluding ambiguous: 0/O/1/I/L).
/// Valid for 30 minutes. Single use.
public struct EnrollmentInvite: Codable, Sendable, Equatable {
    /// 8-char alphanumeric code.
    public let code: String
    public let familyID: FamilyID
    public let childProfileID: ChildProfileID
    public let createdAt: Date
    /// 30 minutes after creation.
    public let expiresAt: Date
    public var used: Bool
    public var usedByDeviceID: DeviceID?
    public var revoked: Bool
    /// Parent's ED25519 public key (base64) for command signature verification.
    /// Delivered to child during enrollment so it can verify parent commands.
    public let commandSigningPublicKeyBase64: String?

    public var isExpired: Bool {
        Date() > expiresAt
    }

    public var isValid: Bool {
        !used && !isExpired && !revoked
    }

    /// Whether this is a parent invite (vs child enrollment).
    public var isParentInvite: Bool {
        childProfileID.rawValue == "__parent_invite__"
    }

    public init(
        code: String,
        familyID: FamilyID,
        childProfileID: ChildProfileID,
        createdAt: Date = Date(),
        expiresAt: Date? = nil,
        used: Bool = false,
        usedByDeviceID: DeviceID? = nil,
        revoked: Bool = false,
        commandSigningPublicKeyBase64: String? = nil
    ) {
        self.code = code
        self.familyID = familyID
        self.childProfileID = childProfileID
        self.createdAt = createdAt
        self.expiresAt = expiresAt ?? createdAt.addingTimeInterval(1800)
        self.used = used
        self.usedByDeviceID = usedByDeviceID
        self.revoked = revoked
        self.commandSigningPublicKeyBase64 = commandSigningPublicKeyBase64
    }
}
